# Auto-generated config file
from easydict import EasyDict as edict

config = edict()
config.margin_list = (1.0, 0.0, 0.4)
config.network = 'vit_s_dp005_mask_0'
config.resume = True
config.save_all_states = True
config.output = 'work_dirs/exp_clip_r50_vs_vit/clip_ratio_15'
config.embedding_size = 512
config.sample_rate = 3.0
config.interclass_filtering_threshold = 0
config.fp16 = True
config.batch_size = 128
config.optimizer = 'adamw'
config.lr = 0.0003
config.weight_decay = 0.1
config.verbose = 2000
config.frequent = 50
config.dali = False
config.dali_aug = False
config.gradient_acc = 1
config.seed = 2048
config.num_workers = 2
config.wandb_key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
config.suffix_run_name = None
config.using_wandb = False
config.wandb_entity = 'entity'
config.wandb_project = 'project'
config.wandb_log_all = True
config.save_artifacts = False
config.wandb_resume = False
config.root_ff = '/DATA/ROIs/ratio_100/train'
config.root_pf = '/DATA/ROIs/variants_dataset/ratio_15/train'
config.val_targets = ['/DATA/ROIs/ratio_100/val', '/DATA/ROIs/variants_dataset/ratio_15/val']
config.train_targets = ['/DATA/ROIs/ratio_100/train', '/DATA/ROIs/variants_dataset/ratio_15/train']
config.num_epoch = 20
config.warmup_epoch = 4
config.teacher_network = 'r50'
config.teacher_model_path = 'work_dirs/config_glint360k_subset_fullface_best_18_01_26/best_model.pt'
config.temperature = 0.07
config.batch_grid_tag = 'clip_ratio_15'
config.num_classes = 63013
config.num_image = 1446728
