# Auto-generated config file
from easydict import EasyDict as edict

config = edict()
config.margin_list = (1.0, 0.0, 0.4)
config.network = 'r50'
config.resume = True
config.save_all_states = True
config.output = 'work_dirs/exp_r50_vs_r50/clip_ratio_60'
config.embedding_size = 512
config.sample_rate = 3.0
config.interclass_filtering_threshold = 0
config.fp16 = True
config.batch_size = 32
config.optimizer = 'adamw'
config.lr = 0.001
config.weight_decay = 0.1
config.verbose = 2000
config.frequent = 50
config.dali = False
config.dali_aug = False
config.gradient_acc = 1
config.seed = 2048
config.num_workers = 4
config.wandb_key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
config.suffix_run_name = None
config.using_wandb = False
config.wandb_entity = 'entity'
config.wandb_project = 'project'
config.wandb_log_all = True
config.save_artifacts = False
config.wandb_resume = False
config.root_ff = '/media/yoav/Yoav/datasets/glint360k/fullface_subset/train'
config.root_pf = '/media/yoav/Yoav/datasets/variants_dataset_subset/ratio_60/train'
config.val_targets = ['/media/yoav/Yoav/datasets/glint360k/fullface_subset/val', '/media/yoav/Yoav/datasets/variants_dataset_subset/ratio_60/val']
config.train_targets = ['/media/yoav/Yoav/datasets/glint360k/fullface_subset/train', '/media/yoav/Yoav/datasets/variants_dataset_subset/ratio_60/train']
config.num_epoch = 2
config.warmup_epoch = 1
config.teacher_network = 'r50'
config.teacher_model_path = 'work_dirs/config_glint360k_subset_fullface_best_18_01_26/best_model.pt'
config.temperature = 0.07
config.batch_grid_tag = 'clip_ratio_60'
config.num_classes = 2101
config.num_image = 48353
config.total_batch_size = 32
config.warmup_step = 1511
config.total_step = 3022
